#!/usr/bin/env python

import re
import os
import sys
import cabal_log

def ended_ok(contents):
  m = re.search("^Registering\s+(\S+)\.\.\.\s*\Z", contents, re.M)
  if m:
    return True
  m = re.search('^Installing executable.s. in', contents, re.M)
  return bool(m)

def build_errors(contents):
  errors = []
  lines = contents.split("\n")
  cabal_log.parse_errors(lines, errors)
  cabal_log.parse_multiline_errors(contents, errors)
  return errors

def main():
  for path in sys.argv[1:]:
    with open(path) as f:
      contents = f.read()

    pkg = os.path.basename(path)
    ok = ended_ok(contents)
    errors = build_errors(contents)

    if ok:
      if errors:
        print "ERROR - {} - ended ok but has errors:".format(pkg)
        for e in errors:
          print "-", e
    else:
      if not errors:
        print "ERROR - {} - did not end ok but no errors found".format(pkg)
      else:
        print "{} - errors:".format(pkg)
        for e in errors: print "-", e

if __name__ == '__main__':
  main()

